### ISSUE TITLE
Add support for IWA Pop-ups

### ISSUE THREAD

**Issue by nicekiwi** [codecentrix/open-twebst#1]
Support for filling and submitting Integrated Windows Authentication pop-ups would be awesome. :smiley:

**Comment by codecentrix** [comment]
Yeah, it is in plan but no ETA. Do you have a public web site that pops up this kind of IWA ?

**Comment by nicekiwi** [comment]
Not a public site exactly, our web platform uses it to auth it's Backend.

On Friday, 30 May 2014, codecentrix notifications@github.com wrote:

> Yeah, it is in plan but no ETA. Do you have a public web site that pops up
> this kind of IWA ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codecentrix/open-twebst/issues/1#issuecomment-44615708
> .

## 

Ezra Sharp
Creative Engineer

KiwiDev

Mobile: (022) 025-9918
Web: www.kiwidev.co.nz

**Comment by codecentrix** [comment]
do you have a quick sample on how to make IWA on the serer side (any language/framework would be fine)?

**Comment by codecentrix** [comment]
will not fix
