### ISSUE TITLE
Issue with IE whenever try to access via OpenTwebstSetup_1.4

### ISSUE THREAD

**Issue by 123Yuvaraj** [codecentrix/open-twebst#3]
I am using OpenTwebstSetup_1.4 to access internet explorer in order to create ticket for the customer query. 

Recent days, I am facing big issue that always giving error as" Failed to Start IE". After trying several times to re-run the macro it started to work again. 

Please do fix this issue and provide us the solution as earliest as possible. 

Regards,
Yuvaraj

**Comment by codecentrix** [comment]
will not fix
